CREATE CONSTRAINT ON (n:Nstory) ASSERT n.url IS UNIQUE;
CREATE INDEX ON :LocalWord(text);

CREATE CONSTRAINT ON (t:Term) ASSERT t.id IS UNIQUE;
CREATE INDEX ON :Term(text);

CREATE CONSTRAINT ON (e:Editor) ASSERT e.name IS UNIQUE;


//CREATE CONSTRAINT ON (w:Word) ASSERT w.text IS UNIQUE;
